name: tilezhan
description: Master Mahjong, One Tile at a Time.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/tiles/
    - assets/mnemonic_png/
    - assets/sounds/
    - assets/sounds/voice/

