name: Print Secrets (one-time)
on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CERT: $APPLE_CERT_PEM_B64"
        env:
          APPLE_CERT_PEM_B64: ${{ secrets.APPLE_CERT_PEM_B64 }}
      - run: echo "KEY: $APPLE_KEY_PEM_B64"
        env:
          APPLE_KEY_PEM_B64: ${{ secrets.APPLE_KEY_PEM_B64 }}
      - run: echo "PROFILE: $BUILD_PROVISION_PROFILE_BASE64"
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
